# fly.toml app configuration file generated for subabot on 2023-08-20T13:21:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "subabot"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
