name: "Backend: Lint & Test"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install the project
        run: cd backend && uv sync --frozen

      - name: Lint the project
        run: source .venv/bin/activate && uv run task lint

      - name: Run tests
        run: source .venv/bin/activate && uv run task test
