name: deploy to deta space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy to deta space
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: lizheming/deta-action@master
        with:
          access_token: ${{ secrets.SPACE_ACCESS_TOKEN }}
          id: ${{ secrets.SPACE_PROJECT_ID }}
          version: "0.1.0"
          notes: "Released automatically with GitHub deta action"
          listed: false
