name: "Prefect: Deploy Flow"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_NAME: subabot

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push Docker image for arm64
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.prefect
          push: true
          tags: ${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:prefect-latest,${{ github.repository_owner }}/${{ env.PROJECT_NAME }}:prefect-${{ github.sha }}
          platforms: linux/arm64,linux/amd64

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Prefect Deploy
        run: |
          cd backend
          uv sync --frozen
          uv run prefect deploy --all --param build=null
